### ISSUE TITLE
Error message when running M-x geben

### ISSUE THREAD

**Issue by zejji** [ahungry/geben#1]
Since upgrading to the current version of geben on MELPA (20160430), I receive the following error message when trying to execute "M-x geben" and the debugging session does not start:

"Symbol's function definition is void: defmacro*"

Previously, I had used geben many times without issue. Oddly, if I remove and reinstall all my packages, geben works for one emacs session, but then the error message reappears on subsequent restarts of emacs.

Further info: I am running GNU Emacs 24.4.1 on Debian Jessie. I have not made any recent changes to my emacs configuration files. All packages are up-to-date (both system packages installed with apt-get and emacs packages installed with the emacs package manager).

**UPDATE:** After experimenting a bit more, I am now able to get geben to run, but M-x geben must executed from a buffer forming part of my project (was this always the case? I may be being forgetful!). I still get the following error message, but thankfully geben still runs:

"../../../../../home/.emacs.d/elpa/geben-20160430.1950/geben.el: `flet' is an obsolete macro (as of 24.3); use either`cl-flet' or `cl-letf'."

**Comment by zejji** [comment]
If it would be helpful to post my .emacs file (which is not especially lengthy), please let me know.

**Comment by ahungry** [comment]
Should be fixed in:

c2e08e8

It may be a day until MELPA has the updated codebase, in the meantime, you can fix it by adding a `(require 'cl)` somewhere in your ~/.emacs before your (require 'geben), or by editing the ELPA installed geben.el and manually applying the update in c2e08e8

**Comment by zejji** [comment]
Great - many thanks!
