### ISSUE TITLE
Default geben-temporary-file-directory is Hard-coded to .emacs.d

### ISSUE THREAD

**Issue by bmag** [ahungry/geben#17]
The default value of `geben-temporary-file-directory` is hard-coded to `(expand-file-name "geben" "~/.emacs.d")`. ([source](https://github.com/ahungry/geben/blob/b1062bc2de3a975fd6b3fac7fdce2cf21608c717/geben.el#L298))

You might want to use `user-emacs-directory` instead of `"~/.emacs.d"`, to accommodate for users that store their emacs directory in a non-standard location.

I've noticed this while reviewing a PR to add Geben support to Spacemacs, so I'm just letting you know.

**Comment by ahungry** [comment]
Thanks for the suggestion, updated in c3887fe

I don't personally use spacemacs, but if you need any changes for compatability with it, let me know.

**Comment by bmag** [comment]
Thank you :smile:
