### ISSUE TITLE
function definition void 

### ISSUE THREAD

**Issue by pranavk** [ahungry/geben#2]
OS: Fedora 23

M-x geben says 'symbol's function definition is void: defstruct'

Any idea what could be wrong ?

**Comment by pranavk** [comment]
I installed this from MELPA

**Comment by ahungry** [comment]
I need to add a fix, it should be ported to calls to cl-defstruct (the alias that allows defstruct to invoke cl-defstruct is added in cl.el which you may not have installed atm, as the package does not explicitly require it).

**Comment by ahungry** [comment]
Fixed https://github.com/ahungry/geben/commit/5d79cfd7cdf79367f2e360cc77c33ff31e31e0e2

**Comment by ahungry** [comment]
@pranavk if you need to fix while you wait for MELPA to update, you can just do a `(require 'cl)` in your init file
