### ISSUE TITLE
name and github description

### ISSUE THREAD

**Issue by ksjogo** [ahungry/geben#20]
Does anybody know the origin of the name geben?

And maybe we should add something with debugging/php/xdebug to the description field.

**Comment by ahungry** [comment]
I'll update the description (or merge it in if one of you beats me to it).

Unfortunately I have no idea where the name originates from.

**Comment by ksjogo** [comment]
I cannot change the github description, would be great if you could add something like xdebug for emacs or so.

**Comment by ahungry** [comment]
Updated to `Geben - PHP xdebug for Emacs`
