### ISSUE TITLE
Update semantic features for Emacs 25.1

### ISSUE THREAD

**Issue by tarsius** [ahungry/geben#22]
The semantic libraries have been renamed in Emacs 25.1, they now also provide "path features", a little used way to provide features. For example what once was `semantic-ctxt.el` now is `semantic/ctxt.el`. Please update the require forms accordingly.

I have noticed this a while ago when performing feature consistency tests for the Emacsmirror. I have also run into some other feature issues with geben: the Emacsmirror contains no packages which provide `wisent-php-tags-wy`, `senator`, and `document`. Where can these packages be found?

**Comment by ksjogo** [comment]
Thanks for the info. Will update the require forms and create a pr.

The functions above are probably not needed anymore, as I am using geben a lot, but never run into them being undefined and did not take special care installing other packages. Will check.

**Comment by ahungry** [comment]
The original geben code that was forked off of google code has been around for awhile - it looks like senator.el is an older package from 2000 (https://www.mail-archive.com/jde@sunsite.auc.dk/msg03870/senator.el)

I also haven't run into any issues where these have actually been called while using the library.

**Comment by ksjogo** [comment]
Ok,the semantic stuff is only used in the etc folder, which the elpa version is installing but not loading at all. So I would be quite surprised if anybody was still using it, even more though, as it should be part of php-mode. I would just remove it.

**Comment by ahungry** [comment]
Sounds good to me, feel free to merge your branch into master and tag (or I'll tag later), as I definitely agree - it seems like leftovers from an earlier time.

**Comment by tarsius** [comment]
Thanks a lot!
