### ISSUE TITLE
Feature:  Would like to see support for nodejs debugging 

### ISSUE THREAD

**Issue by ahungry** [ahungry/geben#27]
I was testing some last night, and I think Geben as is, is close to being able to work with something like node-dbgp package provided by Komodo: http://docs.komodoide.com/Manual/debugnode 

Some things aren't occurring properly atm however - for instance, the fileuri node-dbgp sends in the XML to Geben is a web based URI (such as `/hello.js` instead of `file:///tmp/hello.js`) even when node-dbgp is invoked via the CLI.

Maybe if I run an actual server.js instance of node it will work better?  But atm a simple nodejs script debug session will not work.

The other thing is that unlike the PHP/xdebug integration, the `source` command is not sent, so the file is never even attempted to be opened.  

I'm not sure if these are primarily issues on the node-dbgp end (or if there is a better DBGp debugger for node) or issues we can fix on the Geben side.

**Comment by ksjogo** [comment]
fileuri is fine for me when connecting to the server. But I am not sure if the plugin is up to date anymore.

**Comment by ksjogo** [comment]
Jade is implementing the modern nodejs remote protocol and in general is handling all js stuff, so it is probably not worth the effort to try to fix the wonky unmaintained dbgp extensions for node.
https://github.com/NicolasPetton/jade
7.x in the works https://github.com/NicolasPetton/jade/issues/15

**Comment by ahungry** [comment]
Nice, although I think that is worth mentioning in the README if we're mentioning xdebug and komodo (for python) specifically - the easier it is for users to apply this package to more programs, the better.
