### ISSUE TITLE
Doc: Need working examples of debugging (web/CLI) in other (non-PHP/xdebug) languages 

### ISSUE THREAD

**Issue by ahungry** [ahungry/geben#28]
I notice our documentation (support?) of non-xdebug/PHP is probably lacking.

The geben docs mention it having had support for python/perl/ruby, so if anyone would like to tinker with it and get a minimal stepping session going for each, we may be able to find some info on the Komodo site (see sidebar on http://docs.komodoide.com/Manual/debugnode)

**Comment by djstauffer** [comment]
I use this daily for Perl debugging (using the Komodo Perl libraries).  I could probably set up Python and Ruby also to try them out.  I might be able to do that and produce some documentation.

**Comment by ksjogo** [comment]
Great that it is still working with that, as I(we?) only use it for PHP.
Restructured the README a bit. Would be great if you could add the setup in the sections.

**Comment by ahungry** [comment]
5 years later, no real effort here -  I think https://github.com/emacs-lsp/dap-mode can fill this need better
