### ISSUE TITLE
Auto expand of context vars breaks workflow

### ISSUE THREAD

**Issue by j-hotlink** [ahungry/geben#29]
Been using geben for several years. The new auto expand behaviour of context vars makes things difficult to find (particularly when many hundreds of nodes are rendered), and requires me to manually collapse trees after invoking vars, so I can then begin manual navigation in a controlled manner to the items of interest. I suppose this new behaviour may be beneficial to some, but for me it's proving more than tedious.

Is there a way to restore old behaviour, or at least a recommended way to disable this mechanism?
Thanks.

**Comment by ahungry** [comment]
Are you referring to functionality introduced by 2ce3a7e and 4cd326d ?

**Comment by ksjogo** [comment]
By default nothing *should* (hopefully) auto-expand - geben should preserve if you expanded something between steping/evaling/.... So I would assume that the default state somehow is triggering to expanded on your setup. Which emacs (and geben version) are you using?

**Comment by j-hotlink** [comment]
I'm afraid I can't tell if those commits are the cause or not.

I've experienced the behaviour on Emacs 24, using geben installed via package manager (my historical installations were made outside of package manager via the original geben repo on Emacs 23 or 24). In my case(s) when the new icons are used (ie: installed via emacs package not old geben repo) I experience the behaviour: each keypress of "v" refreshes the context tree, expands all child nodes, and sends the cursor on a goose-chase during rendering causing the buffer to scroll excitedly.

I use the same .emacs file across installations, so don't suspect config. I'm not at an offending machine right now so can't quote the exact geben version, however when I raised the issue the package had been installed a few days prior, so presumably the latest version.

I can test another installation using the packaged version next week to confirm results if helpful.

**Comment by ksjogo** [comment]
It looks like the problem lies in the xdebug return value for the location of the variable which was used to identify expanded values. For
Some reason "" is returned in some cases causing more stuff to expand than intended. Will further look into that.

**Comment by ksjogo** [comment]
Just pushed a patch. Could you install the new master and try that one please?

**Comment by ksjogo** [comment]
Used it for two days and everything feels good.
