### ISSUE TITLE
Infinite loop calling property_get

### ISSUE THREAD

**Issue by djstauffer** [ahungry/geben#30]
I had a conversation about this problem with the original creator/mainter of geben.  You can find a description of the problem here:

https://github.com/djstauffer/geben-on-emacs/commit/349b19c1cf498980843eb629bf2151d0f1696c04

After our email conversation about a patch I submitted for it, HANAI Tohru modified it to allow it to work with either PHP or Perl (my patch was solely targeted at Perl, because that is where I found the problem).

Evidently HANAI Tohru never got around to applying the patch to his repo.  I guess I'm not surprised, since he already wasn't working on geben in August of 2015 when I submitted the patch.

Below is the patch which fixes the problem.  It is for the geben.el file for the latest commit from 17 days ago ( https://github.com/ahungry/geben/commit/ef154269e7275a5ececa7205b125093eea3d6887 ).

Let me know if you have any further questions about this.

<pre>
2493,2503c2493,2497
<          (let* ((initmsg (geben-session-initmsg session))
<                 (lang (xml-get-attribute-or-nil initmsg 'language)))
<            (mapcar (lambda (key)
<                      (let ((arg (plist-get (car args) key)))
<                        (when arg
<                          (cons (geben-cmd-param-for key)
<                                (if (and (eq key :name)
<                                         (not (string= lang "PHP")))
<                                  (geben-dbgp-escape-param-arg arg)
<                                  arg)))))
<                    '(:depth :context-id :name :max-data-size :type :page :key :address)))))
---
>          (mapcar (lambda (key)
>                    (let ((arg (plist-get (car args) key)))
>                      (when arg
>                        (cons (geben-cmd-param-for key) arg))))
>                  '(:depth :context-id :name :max-data-size :type :page :key :address))))
2505,2515d2498
< (defun geben-dbgp-escape-param-arg (param)
<   (if (stringp param)
<     (concat
<       "\""
<       (replace-regexp-in-string
<         "*" "\\\\*"
<         (replace-regexp-in-string
<           "\"" "\\\\\""
<           param))
<       "\"")
<     param))
</pre>

**Comment by ksjogo** [comment]
Just pushed that into a new branch but I do not have a perl set up for verifying functionality.

**Comment by ksjogo** [comment]
Ran the code yesterday and php is still working, so that's fine for me. Merged and thanks for the fix.

**Comment by djstauffer** [comment]
cool.  Glad to be of help.
