### ISSUE TITLE
Allow output to be displayed only after script is finished executing

### ISSUE THREAD

**Issue by danlamanna** [ahungry/geben#36]
At the moment, I'm debugging a CLI script that is iterating and printing output for each file. I have a conditional breakpoint set for a file far down in the list, in the mean time emacs is unusable since geben is calling `pop-to-buffer` on the output buffer for every single line of output.

It would be nice if geben (optionally) wouldn't call the `geben-display-window-function` until execution is completed.

**Comment by ksjogo** [comment]
Afair I put in some output blocker at some point. Need to check that.

Could you provide some free example so we can validate the new/wanted behaviour with that?

**Comment by danlamanna** [comment]
Something as simple as this should do it:
```
<?php

for ($i=0; $i<100; $i++) {
    echo "foo";
    sleep(1);
}
```

Set a conditional breakpoint for when `$i == 50` for example, and just let it run. Every second, it will pop the output buffer to the front - no matter which frame you're in.

**Comment by ksjogo** [comment]
Ah, ok, long time since I did echoing scripts. :D 
Cannot reproduce the pop to buffer here. 
There is the customization `geben-show-redirect-buffers`, just set that to nil so it will not auto pop to it.
