### ISSUE TITLE
Any useful fixes/enhancements in other forks of geben ?

### ISSUE THREAD

**Issue by phil-s** [ahungry/geben#44]
This seems like the most active fork of geben, so I'm wondering whether there are any improvements made by others which could be merged?

https://github.com/fallchildren/geben-on-emacs/commits/my-dev had a fair few commits made to it.  Perhaps it's worth reviewing those and seeing whether any are applicable here?

**Comment by ahungry** [comment]
I'll have to check out, if any stick out to you, let us know!

**Comment by ksjogo** [comment]
We ported some commits from https://github.com/JDHankle/riviera
