### ISSUE TITLE
geben-path-mappings documentation

### ISSUE THREAD

**Issue by kgrossjo** [ahungry/geben#45]
The documentation for `geben-path-mappings` should provide more detail about the data structure.  Right now, it says:

> Path mappings for setting breakpoints in VMs/containers/other spaceships.

Information that is missing:

* Each path mapping is a two-element list.
* The first element is the path name on the host (i.e., the computer running Emacs).
* The second element is the path name on the server (i.e., the VM/container/other spaceship running PHP).

There are other similar tools where two path names are swapped, so it's very important to mention the order.

I wonder if `M-x customize-variable` could be told to display different labels, right now it shows "String" for the first element and "String" for the second element.  If it could show "Path on host" for the first element and "Path on VM/container" for the second element, that might help substantially.

**Comment by aanoaa** [comment]
current status

> Add a mapping from files on the host to files on the vm/docker image with M-x customize-variable geben-path-mappings or set in emacs config with (setq geben-path-mappings '(("\<project base on host\>" "\<project base on vm\>"))

**Comment by ahungry** [comment]
Someone can PR this, but until then, I'll go ahead and close.
