### ISSUE TITLE
Is there a way to show breakpoints in the fringe and add breakpoints via mouse?

### ISSUE THREAD

**Issue by echosa** [ahungry/geben#46]
Looking at the `gdb` section of the Emacs manual, it appears as though Emacs supports the ability show breakpoints in the fringe and allow setting breakpoints by clicking the fringe with the mouse. Is there a way to do these things using geben?

**Comment by ksjogo** [comment]
I don't think it is currently implemented. Probably would require use of the path mapping feature.

**Comment by ahungry** [comment]
Closing this, if someone wants to add it, feel free to make the PR :smile:
