### ISSUE TITLE
"geben-end" command is broken

### ISSUE THREAD

**Issue by zilti** [ahungry/geben#49]
It sometimes just breaks. Often, it doesn't terminate the process buffer. Even when I kill it manually after, it will still refuse to accept new connections.

**Comment by ksjogo** [comment]
Is this 7? Or also happening on 5?

**Comment by zilti** [comment]
PHP 7, yes.

**Comment by ahungry** [comment]
I just tested, it worked fine for me on Emacs 28 with latest geben.

**Comment by epeters-jrmngndr** [comment]
I have this same problem on Emacs 28, latest geben, via Doom Emacs distribution. I use "Geben run", and by the end, I get into a state where an error is shown when Geben connections try to initiate - "Rejected new connection from <IP> (Already in debugging)."

I hope to look into this in the future but I am no elisp expert. Any information I could provide which would help maintainers I am happy to give. I am debugging a PHP project running inside a docker container, with pretty standard xdebug forwarding on a custom port. 

This is on macos.

**Comment by epeters-jrmngndr** [comment]
This seems to happen when you have multiple php files that get invoked via JS.

**Comment by epeters-jrmngndr** [comment]
What seems to be happening is that (defun geben-dbgp-session-accept-p ...) invokes are failing for me, with this message:
>       (message "GEBEN: Rejected new connection from %s (Already in debugging)"

This is after running 'geben-end' and 'geben-stop'. There seems to be no way to fix this once it happens, except quit emacs and restart.

I am going to keep experimenting with the internal variables and see if I can figure out why this is failing.

FYI - @ahungry

**Comment by mallt** [comment]
@emil-r-petersen Could you try to to clear the geben storage file that's located in the folder `$HOME/.emacs.d/geben/.storage` after running `geben-end`? Do things start working as expected again afterwards?

**Comment by epeters-jrmngndr** [comment]
@mallt  They don't no, after 'rm ~/.emacs.d/geben/.storage'. The file didn't get recreated either.

**Comment by mallt** [comment]
@emil-r-petersen Ok, and does it help if you clear all breakpoints and predefined breakpoints after running `geben-end` (`geben-clear-predefined-breakpoints` and `geben-clear-breakpoints`), and then restart geben?

**Comment by epeters-jrmngndr** [comment]
@mallt  Sorry for the slow response - It does not. I used geben run, works fine on the first go (runs through the program, opens output in a buffer), but even after manually removing breakpoints (Hadn't set any that time), starting geben again with `geben` fails. 

If there was another way to restart geben, I'm not aware of it. ~/.emacs.d/geben/.storage still hasn't been re-created either, not sure if that matters.

**Comment by epeters-jrmngndr** [comment]
@mallt  On a second try, that _did_ fix the problem. I ran the two commands you sent, then geben end, then geben stop (which I think was unnecessary).

And then, when I reload my page, I'm dropped back into geben. Thanks!

**Comment by ahungry** [comment]
Sounds resolved, thanks everyone for assisting!
