### ISSUE TITLE
How can I set breakpoints in my working file?

### ISSUE THREAD

**Issue by daraul** [ahungry/geben#52]
I'm using geben, with phpunit and I can't seem to set any breakpoints in my php file, until I do the following:

- `C-x geben`
- `C-x phpunit-current-test`
-  While in the phpunit buffer: `C-c f <the test file>`
- Go to the line I want to break on and do `C-x geben-set-breakpoint-line`

It will then break on that line, but isn't there some way to I could have `C-x geben-set-breakpoint-line` work from the file I'm already editing?

**Comment by ksjogo** [comment]
I don't know what the phpunit-current-test does to the buffers/if it creates new files/etc.
You could potentially use the pathmapping functioniality: https://github.com/ahungry/geben#vms

**Comment by daraul** [comment]
I'm not sure what it does to the buffer itself, but I can see the line gets highlighted when I do `C-x geben-set-breakpoint-line` after I follow the steps above. 

If I just do that while editing the file I want the breakpoint in, though, I get no highlight.

**Comment by mallt** [comment]
Could you try if it works to add the breakpoint with `M-x geben-add-current-line-to-predefined-breakpoints`?

**Comment by daraul** [comment]
That works! So what's the difference between `geben-add-current-line-to-predefined-breakpoints` and `geben-set-breakpoint-line`?

It doesn't highlight the line, though, which would have been nice.

**Comment by mallt** [comment]
`geben-set-breakpoint-line` requires an active geben session, whereas `geben-add-current-line-to-predefined-breakpoints` can be used to set breakpoints before the geben session is started.

**Comment by daraul** [comment]
I'll close this, then, but is there some way I can get the line highlighted outside of geben, though?
