### ISSUE TITLE
What about XDebug 3.*?

### ISSUE THREAD

**Issue by rakotomandimby** [ahungry/geben#55]
README is about 2.* versions of XDebug, but I guess XDebug 3 is not that way different?

**Comment by ahungry** [comment]
The xdebug documentation has a translation recommendation from 2.x flags to 3.x flags here:

https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_enable

I translated it to this command roughly (I'll toss it in the readme):
```
php -d xdebug.mode=debug -d xdebug.client_host=127.0.0.1 -d xdebug.client_port=9000 -d xdebug.remote_handler=dbgp -d xdebug.idekey=geben -d xdebug.start_with_request=yes /tmp/gebenTest.php
```

**Comment by ahungry** [comment]
added in ae892bb
