### ISSUE TITLE
Is geben working for anybody?

### ISSUE THREAD

**Issue by odysseyalive** [ahungry/geben#56]
Odd question, I know.  It's been about three to four years since I last used Geben with Xdebug successfully.  I use the Vim Vdebug plugin with the following setup just fine.  However, I have some larger projects that run more smoothly in emacs.

I'd feel better just hearing someone's running geben.  There aren't any recent posts here to confirm that.  I've sunk some hours trying to debug geben, but I can't seem to get the xdebug init string to be read by the geben session. 

My current setup:
Host Machine: Rhel 8
Emacs 28.1.50

VM setup:
Rootless Container: Rhel 8
Host: 127.0.0.1
PHP 7.4.29
Xdebug: 2.9.8
Xdebug Settings:
xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9003
xdebug.remote_handler=dbgp
xdebug.idekey=geben
xdebug.remote_autostart=1
xdebug.scream=0
xdebug.cli_color=1
xdebug.remote_log='/tmp/xdebug.log'
xdebug.force_display_errors=1

Geben is installed.  I added some mapping:

![alt text](https://i.imgur.com/Q3cFXto.png)

I opened the php file, added a predefined breakpoint.

![alt text](https://i.imgur.com/6vKFfG9.png)

Started geben and loaded the page...

![alt text](https://i.imgur.com/gG1BdcD.png)

From this next image, you can see where I can add manual commands using the buffer created by geben.  The top of this image is the output from the xdebug log file showing there's communication.  I can even manually add breakpoints.

![alt text](https://i.imgur.com/GB78v1s.png)

I'm still trying to make friends with the geben.el script.  From what I gather, the initial init xml is never being pulled into the geben session filter.  So geben mode never has a chance to activate.

I can see my session in the geben-sessions variable:

![alt text](https://i.imgur.com/hjE70jy.png)

However, the temporary directory is never initialized.  Niether is the variable for geben-current-session.

I've tried compiling emacs in 26, 27 and 28.  I get pretty much the same results.

Because there isn't a geben-current-session, none of the geben commands work... except geben_end.

Any ideas on where I might look when debugging geben.el?

**Comment by odysseyalive** [comment]
I also noticed in the geben-remote-p function, there are some exclusions for localhost.  The geben path mappings should pull in regardless of  whether the port 127.0.0.1 is used or not, right?  Such is the life of rootless containers...  The last time geben was working for me, it was in a vagrant box which uses a static host.

**Comment by ahungry** [comment]
I rarely use it (a few others here have been more active than myself in maintaining/adding new updates).

**Comment by odysseyalive** [comment]
I wasn't smart enough to figure it out.  I had a hard time tracking the processes with the native debugger in Emacs.  From what I gather,  it looked like line 785 in dbgp.el wasn't firing.  

When I manually added a line to the dbgp-session-filter to run the geben-dbgp-session-filter everything started working -- except the variable view -- which was just showing blank.

I spent quite a bit of time on it and needed to move forward and got wrapped up in dap-mode which seems to be working out of the box for my situation.

**Comment by gazzatav** [comment]
@bridgesense I tried it this week and it looks like it wants to do something when I go into geben-mode but the geben command itself just tells me it's waiting to connect and nothing else happens.  Could you share more about that fix that you made, I'd be happy just to be able to step through my code.

**Comment by ahungry** [comment]
It's always someone's contribution that I take too willingly that screws it up (pretty much across all repos) - I tried an earlier commit in history, prior to this change that added "unicode support", and now it works for me just fine.

https://github.com/j-hotlink/geben/commit/ebef742f70e6cd559f1f5fd3965a78233942b249

https://github.com/ahungry/geben/issues/48 (referenced/suggested here)

It's possible the j-hotlink fork (of a detached head fork) had other changes that are required for it to work.  Unfortunately, no one provided feedback post-merge (other than this thread, noting it wasn't working).

I'm going to revert d3706387ed25b3037338572f3968b4cc2d8825a0 and dd05dc37d17947bb5bfbc1969ba6f0c8d5a43016 so it can work as it did prior to this change, and if anyone needs whatever that other fork offers (further unicode support), they can use that as their base.

**Comment by ahungry** [comment]
Reversions done a580dff8cc6ac9ab363b056a91a397d3bc3f69d9 and 8b40146ea3a133748ba2950763ff578350c19f7e 

I believe this should once again work as expected - please feel free to comment and let me know if not.
